### ISSUE TITLE
Could not load classifier cascade .

### ISSUE THREAD

**Issue by vishnums** [katotetsuro/ofxLibface#1]
When i try to run the code in open-frameworks it gives me it outputs the about message...
Where can i locate the haarcascade files...
I have made the project with ofxcv and ofxopencv along with ofxlibface
Thanks

**Comment by vishnums** [comment]
Done :) I changed the libface.h to point towards haarcascade directory :) Thanks for the addon

**Comment by katotetsuro** [comment]
@vishnums Thank you for your feedback!
Certainly, you're right.
I think it should be loaded by "ofToDataPath" for OF-style :)
